'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
 await queryInterface.bulkInsert('users', [{
  "id": 1,
  "name": "Hilarius",
  "surname": "De Roberto",
  "birthDate": "1999-09-09",
  "email": "hderoberto0@ezinearticles.com",
  "password": "F2lDyUpt",
  "categoryUserId": 1,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 2,
  "name": "Bea",
  "surname": "Krzysztof",
  "birthDate": "1982-06-01",
  "email": "bkrzysztof1@mysql.com",
  "password": "4oVgApc",
  "categoryUserId": 1,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 3,
  "name": "Hyatt",
  "surname": "Luisetti",
  "birthDate": "1979-05-14",
  "email": "hluisetti2@google.pl",
  "password": "xVKtxPeP",
  "categoryUserId": 2,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 4,
  "name": "Pat",
  "surname": "Treswell",
  "birthDate": "2004-11-15",
  "email": "ptreswell3@liveinternet.ru",
  "password": "dwli2DE7Y",
  "categoryUserId": 2,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 5,
  "name": "Vidovic",
  "surname": "MacGiffin",
  "birthDate": "1986-12-14",
  "email": "vmacgiffin4@xinhuanet.com",
  "password": "IBDJPUk",
  "categoryUserId": 2,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 6,
  "name": "Rafaelia",
  "surname": "Rammell",
  "birthDate": "1981-10-20",
  "email": "rrammell5@dyndns.org",
  "password": "UJgn6WI",
  "categoryUserId": 2,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 7,
  "name": "Nikolaos",
  "surname": "Noquet",
  "birthDate": "2005-08-16",
  "email": "nnoquet6@dropbox.com",
  "password": "IXGwBu",
  "categoryUserId": 2,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 8,
  "name": "Laurie",
  "surname": "Gothard",
  "birthDate": "1975-01-04",
  "email": "lgothard7@ebay.com",
  "password": "sP5uVuo",
  "categoryUserId": 1,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 9,
  "name": "Barret",
  "surname": "Huguenet",
  "birthDate": "1984-10-25",
  "email": "bhuguenet8@tripod.com",
  "password": "lyUNs2aI",
  "categoryUserId": 1,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 10,
  "name": "Carmen",
  "surname": "Carlaw",
  "birthDate": "2004-10-22",
  "email": "ccarlaw9@thetimes.co.uk",
  "password": "cjqAnRO",
  "categoryUserId": 1,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 11,
  "name": "Bobbette",
  "surname": "Kiezler",
  "birthDate": "1988-10-23",
  "email": "bkiezlera@wordpress.com",
  "password": "aeLMeZ",
  "categoryUserId": 2,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 12,
  "name": "Babbie",
  "surname": "Swaysland",
  "birthDate": "1991-09-15",
  "email": "bswayslandb@geocities.jp",
  "password": "DyjeuBQq6sq",
  "categoryUserId": 2,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 13,
  "name": "Harli",
  "surname": "Tremelling",
  "birthDate": "1976-05-05",
  "email": "htremellingc@eepurl.com",
  "password": "EupHdQJ3",
  "categoryUserId": 1,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 14,
  "name": "Mordecai",
  "surname": "McCray",
  "birthDate": "1974-08-18",
  "email": "mmccrayd@springer.com",
  "password": "CpTUkHP",
  "categoryUserId": 1,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 15,
  "name": "Kristi",
  "surname": "McNab",
  "birthDate": "1988-07-27",
  "email": "kmcnabe@edublogs.org",
  "password": "tFnhmiHQuq4",
  "categoryUserId": 2,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 16,
  "name": "Avram",
  "surname": "Luckman",
  "birthDate": "2000-05-25",
  "email": "aluckmanf@shinystat.com",
  "password": "WhohwH4nFEG",
  "categoryUserId": 2,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 17,
  "name": "Jacquette",
  "surname": "Cookley",
  "birthDate": "2002-02-20",
  "email": "jcookleyg@twitter.com",
  "password": "oJmJaHJv51",
  "categoryUserId": 1,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 18,
  "name": "Corney",
  "surname": "Nutty",
  "birthDate": "2006-12-01",
  "email": "cnuttyh@msn.com",
  "password": "gDAVGwaXEPqK",
  "categoryUserId": 2,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 19,
  "name": "Georgianna",
  "surname": "Corradi",
  "birthDate": "1971-10-27",
  "email": "gcorradii@vistaprint.com",
  "password": "1QwAQPMU",
  "categoryUserId": 1,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 20,
  "name": "Rudie",
  "surname": "Pollington",
  "birthDate": "1971-08-06",
  "email": "rpollingtonj@yandex.ru",
  "password": "yj2VgO",
  "categoryUserId": 1,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 21,
  "name": "Amii",
  "surname": "Dugall",
  "birthDate": "1993-12-01",
  "email": "adugallk@yale.edu",
  "password": "SH9DfWhPnS",
  "categoryUserId": 1,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 22,
  "name": "Hebert",
  "surname": "Dot",
  "birthDate": "1974-09-24",
  "email": "hdotl@tumblr.com",
  "password": "ONL38DvT",
  "categoryUserId": 2,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 23,
  "name": "Hernando",
  "surname": "Cornew",
  "birthDate": "1992-10-30",
  "email": "hcornewm@macromedia.com",
  "password": "NafsHA",
  "categoryUserId": 2,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 24,
  "name": "Leonid",
  "surname": "Chaimson",
  "birthDate": "1997-08-24",
  "email": "lchaimsonn@instagram.com",
  "password": "XTGwa8z2egm",
  "categoryUserId": 1,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 25,
  "name": "Farlie",
  "surname": "Tremoille",
  "birthDate": "2010-03-01",
  "email": "ftremoilleo@accuweather.com",
  "password": "9d5c676",
  "categoryUserId": 2,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 26,
  "name": "Ailene",
  "surname": "Manders",
  "birthDate": "2002-12-28",
  "email": "amandersp@samsung.com",
  "password": "YDZ63b7tNTVn",
  "categoryUserId": 1,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 27,
  "name": "Agnese",
  "surname": "Southerell",
  "birthDate": "1982-03-02",
  "email": "asoutherellq@diigo.com",
  "password": "uQceWZ3Hc",
  "categoryUserId": 1,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 28,
  "name": "Salvador",
  "surname": "Gosnay",
  "birthDate": "2000-09-08",
  "email": "sgosnayr@mac.com",
  "password": "LO8LmFQGkC",
  "categoryUserId": 1,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 29,
  "name": "Pattin",
  "surname": "Clewer",
  "birthDate": "1980-03-23",
  "email": "pclewers@is.gd",
  "password": "4BK0xliEVN",
  "categoryUserId": 2,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 30,
  "name": "Elvira",
  "surname": "Maas",
  "birthDate": "1970-10-12",
  "email": "emaast@fotki.com",
  "password": "MyKZGY",
  "categoryUserId": 1,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 31,
  "name": "Cirillo",
  "surname": "Coltart",
  "birthDate": "1999-06-25",
  "email": "ccoltartu@usnews.com",
  "password": "xjIbeCxsvw2",
  "categoryUserId": 1,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 32,
  "name": "Francesca",
  "surname": "Furzey",
  "birthDate": "1971-10-18",
  "email": "ffurzeyv@squarespace.com",
  "password": "8GBaL2F",
  "categoryUserId": 1,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 33,
  "name": "Daniella",
  "surname": "Gonnely",
  "birthDate": "1993-11-28",
  "email": "dgonnelyw@scribd.com",
  "password": "33psJXOO",
  "categoryUserId": 2,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 34,
  "name": "Rafaellle",
  "surname": "Bertrand",
  "birthDate": "1982-07-06",
  "email": "rbertrandx@networksolutions.com",
  "password": "mg0CJyl",
  "categoryUserId": 2,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 35,
  "name": "Chelsae",
  "surname": "Leonard",
  "birthDate": "1988-08-16",
  "email": "cleonardy@wikia.com",
  "password": "MWn4ByZJFB",
  "categoryUserId": 1,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 36,
  "name": "Brynne",
  "surname": "Cridge",
  "birthDate": "1984-10-05",
  "email": "bcridgez@w3.org",
  "password": "ao5F7Yp0aTo",
  "categoryUserId": 1,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 37,
  "name": "Barth",
  "surname": "Motherwell",
  "birthDate": "1976-10-05",
  "email": "bmotherwell10@seattletimes.com",
  "password": "dghullj",
  "categoryUserId": 2,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 38,
  "name": "Miguel",
  "surname": "Poxson",
  "birthDate": "2008-03-10",
  "email": "mpoxson11@issuu.com",
  "password": "JMgnyLR",
  "categoryUserId": 2,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 39,
  "name": "Babs",
  "surname": "Blaydon",
  "birthDate": "1981-06-08",
  "email": "bblaydon12@smugmug.com",
  "password": "CjBIQnlnE",
  "categoryUserId": 2,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 40,
  "name": "Annabela",
  "surname": "Jouhandeau",
  "birthDate": "1980-04-22",
  "email": "ajouhandeau13@google.it",
  "password": "ELtClB5AT",
  "categoryUserId": 1,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 41,
  "name": "Cristi",
  "surname": "Bickerdicke",
  "birthDate": "1978-02-21",
  "email": "cbickerdicke14@imdb.com",
  "password": "p1Wfzs8i3",
  "categoryUserId": 2,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 42,
  "name": "Kiel",
  "surname": "Lyles",
  "birthDate": "2008-08-20",
  "email": "klyles15@adobe.com",
  "password": "JxFJEHD3S",
  "categoryUserId": 1,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 43,
  "name": "Hedvige",
  "surname": "Meagh",
  "birthDate": "2002-01-23",
  "email": "hmeagh16@nationalgeographic.com",
  "password": "gO7DAw",
  "categoryUserId": 2,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 44,
  "name": "Mahalia",
  "surname": "McCoish",
  "birthDate": "1992-09-13",
  "email": "mmccoish17@eepurl.com",
  "password": "ceo3co3nQBc",
  "categoryUserId": 2,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 45,
  "name": "Liv",
  "surname": "Records",
  "birthDate": "1982-10-06",
  "email": "lrecords18@telegraph.co.uk",
  "password": "yNM1MYffk",
  "categoryUserId": 2,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 46,
  "name": "Benny",
  "surname": "Calvie",
  "birthDate": "1989-09-23",
  "email": "bcalvie19@noaa.gov",
  "password": "9yQEuSnU",
  "categoryUserId": 1,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 47,
  "name": "Olivia",
  "surname": "Lockey",
  "birthDate": "1975-06-07",
  "email": "olockey1a@dagondesign.com",
  "password": "3Fh3yb53fHyL",
  "categoryUserId": 1,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 48,
  "name": "Mead",
  "surname": "Sorensen",
  "birthDate": "1976-02-03",
  "email": "msorensen1b@answers.com",
  "password": "nj2ApAGvp",
  "categoryUserId": 1,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 49,
  "name": "Denise",
  "surname": "Kearey",
  "birthDate": "1972-09-21",
  "email": "dkearey1c@fc2.com",
  "password": "VasqWS8k",
  "categoryUserId": 2,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}, {
  "id": 50,
  "name": "Jori",
  "surname": "Frascone",
  "birthDate": "1973-02-04",
  "email": "jfrascone1d@soundcloud.com",
  "password": "Yvv4Vy91PD",
  "categoryUserId": 2,
  "profileImage": "/images/default_and_logos/default_avatar.svg"
}]
, {});
    
  },

  down: async (queryInterface, Sequelize) => {
     await queryInterface.bulkDelete('users', null, {});
     
  }
};
