'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
      await queryInterface.bulkInsert('reviews', [
      {"id":1,"titleReview":"Bar Review","comments":"vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus","stars":1,"productId":"92"},
      {"id":2,"titleReview":"Mat Review","comments":"odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla","stars":2,"productId":"015"},
      {"id":3,"titleReview":"Weight Review","comments":"proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices","stars":3,"productId":"94"},
      {"id":4,"titleReview":"Elastic-Band Review","comments":"lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis","stars":4,"productId":"6"},
      {"id":5,"titleReview":"Mat Review","comments":"magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque","stars":5,"productId":"579"},
      {"id":6,"titleReview":"Weight Review","comments":"tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor","stars":5,"productId":"73307"},
      {"id":7,"titleReview":"Mat Review","comments":"justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum","stars":2,"productId":"9901"},
      {"id":8,"titleReview":"Mat Review","comments":"quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet","stars":4,"productId":"456"},
      {"id":9,"titleReview":"Bar Review","comments":"aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi","stars":5,"productId":"55"},
      {"id":10,"titleReview":"Bar Review","comments":"sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat","stars":3,"productId":"2062"},
      {"id":11,"titleReview":"Weight Review","comments":"integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit","stars":3,"productId":"3"},
      {"id":12,"titleReview":"Bar Review","comments":"volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in","stars":3,"productId":"7"},
      {"id":13,"titleReview":"Weight Review","comments":"purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient","stars":4,"productId":"77995"},
      {"id":14,"titleReview":"Bar Review","comments":"donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu","stars":4,"productId":"703"},
      {"id":15,"titleReview":"Bar Review","comments":"sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget","stars":1,"productId":"2352"},
      {"id":16,"titleReview":"Elastic-Band Review","comments":"vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum","stars":2,"productId":"67"},
      {"id":17,"titleReview":"Bar Review","comments":"magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris","stars":4,"productId":"0555"},
      {"id":18,"titleReview":"Weight Review","comments":"dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris","stars":4,"productId":"9098"},
      {"id":19,"titleReview":"Weight Review","comments":"nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit","stars":3,"productId":"0"},
      {"id":20,"titleReview":"Bar Review","comments":"consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae","stars":5,"productId":"50241"},
      {"id":21,"titleReview":"Weight Review","comments":"amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit","stars":3,"productId":"9"},
      {"id":22,"titleReview":"Mat Review","comments":"at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci","stars":2,"productId":"2120"},
      {"id":23,"titleReview":"Bar Review","comments":"cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien","stars":3,"productId":"8"},
      {"id":24,"titleReview":"Elastic-Band Review","comments":"mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum","stars":4,"productId":"08408"},
      {"id":25,"titleReview":"Bar Review","comments":"nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante","stars":5,"productId":"14"},
      {"id":26,"titleReview":"Elastic-Band Review","comments":"lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc","stars":2,"productId":"583"},
      {"id":27,"titleReview":"Weight Review","comments":"sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa","stars":2,"productId":"415"},
      {"id":28,"titleReview":"Elastic-Band Review","comments":"amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis","stars":3,"productId":"766"},
      {"id":29,"titleReview":"Elastic-Band Review","comments":"porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum","stars":2,"productId":"2"},
      {"id":30,"titleReview":"Mat Review","comments":"ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse","stars":3,"productId":"01495"},
      {"id":31,"titleReview":"Weight Review","comments":"a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit","stars":4,"productId":"02"},
      {"id":32,"titleReview":"Bar Review","comments":"vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi","stars":2,"productId":"190"},
      {"id":33,"titleReview":"Elastic-Band Review","comments":"cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum","stars":3,"productId":"4"},
      {"id":34,"titleReview":"Elastic-Band Review","comments":"maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus","stars":4,"productId":"3"},
      {"id":35,"titleReview":"Bar Review","comments":"nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis","stars":5,"productId":"812"},
      {"id":36,"titleReview":"Elastic-Band Review","comments":"blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in","stars":3,"productId":"0"},
      {"id":37,"titleReview":"Bar Review","comments":"sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam","stars":3,"productId":"73"},
      {"id":38,"titleReview":"Elastic-Band Review","comments":"tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla","stars":3,"productId":"201"},
      {"id":39,"titleReview":"Elastic-Band Review","comments":"montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum","stars":5,"productId":"358"},
      {"id":40,"titleReview":"Bar Review","comments":"eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor","stars":4,"productId":"669"},
      {"id":41,"titleReview":"Weight Review","comments":"consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non","stars":4,"productId":"69"},
      {"id":42,"titleReview":"Mat Review Review","comments":"semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at","stars":4,"productId":"73135"},
      {"id":43,"titleReview":"Elastic-Band Review","comments":"in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy","stars":3,"productId":"3630"},
      {"id":44,"titleReview":"Bar Review","comments":"habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt","stars":4,"productId":"295"},
      {"id":45,"titleReview":"Weight Review","comments":"a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at","stars":5,"productId":"6887"},
      {"id":46,"titleReview":"Bar Review","comments":"duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse","stars":4,"productId":"8"},
      {"id":47,"titleReview":"Elastic-Band Review","comments":"duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel","stars":3,"productId":"672"},
      {"id":48,"titleReview":"Bar Review","comments":"augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst","stars":3,"productId":"201"},
      {"id":49,"titleReview":"Mat Review","comments":"feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa","stars":4,"productId":"118"},
      {"id":50,"titleReview":"Bar Review","comments":"non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh","stars":5,"productId":"73129"}], {});
    
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('reviews', null, {});
  }
};